### ISSUE TITLE
Ruby / CoffeeScript Style Interpolation

### ISSUE THREAD

**Issue by skorecky** [avand/sprinkles#30]
This would obviously be done in sprinkles flavor but wanted to post the idea here to see what you thought. Especially because it uses eval which not a fan of but maybe you would have another idea.

But thought it would be cool to do "this is my awesome ${someVar}"
```javascript
var test = "TEST";

var parseString = function() {
  return this.replace(/#\{(.*?)\}/g,
    function(whole, expr) {
      return eval(expr);
  });
};

String.prototype.parseString = parseString;

// "this is my #{test} string".parseString() 
// "this is my TEST string"
```

**Comment by avand** [comment]
ES6 now is introducing the backtick template strings: `The %{adj} brown fox`. So this issue is headed in the wrong direction.
